In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.font_manager

In [2]:
from pyod.models.abod import ABOD
from pyod.models.knn import KNN

In [3]:
df = pd.read_csv("rca.csv")

In [4]:
df.head(100)

trace_id      timestamp  latency  succ      source      target
0   868d91717444d4112006  1587398400084      4.0  True  docker_005      db_003
1   868d91717444d4112006  1587398400090      2.0  True  docker_005      db_003
2   868d91717444d4112006  1587398400084      2.0  True  docker_005  docker_005
3   868d91717444d4112006  1587398400054     40.0  True  docker_004  docker_005
4   868d91717444d4112006  1587398400053      0.0  True  docker_004  docker_004
..                   ...            ...      ...   ...         ...         ...
95  2190e1717444d4129924  1587398400290      1.0  True  docker_001      db_009
96  2190e1717444d4129924  1587398400287      4.0  True  docker_001  docker_001
97  2190e1717444d4129924  1587398400296      1.0  True  docker_001      db_009
98  2190e1717444d4129924  1587398400292      4.0  True  docker_001  docker_001
99  2190e1717444d4129924  1587398400300      1.0  True  docker_001      db_009

[100 rows x 6 columns]

In [5]:
detector = KNN()
detector.fit(df.iloc[:,1:4])

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [6]:
previsoes = detector.labels_
previsoes

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [7]:
np.unique(previsoes, return_counts=True)

(array([0, 1]), array([539,  60]))

In [8]:
confianca_previsoes = detector.decision_scores_
confianca_previsoes

array([1.41421356e+00, 2.00000000e+00, 1.41421356e+00, 1.40356688e+01,
       7.00000000e+00, 3.60555128e+00, 3.00000000e+00, 3.16227766e+00,
       2.00000000e+00, 2.00000000e+00, 9.48683298e+00, 2.00000000e+00,
       3.00000000e+00, 2.23606798e+00, 3.00000000e+00, 2.23606798e+00,
       3.60555128e+00, 7.81024968e+00, 3.00000000e+00, 2.23606798e+00,
       2.82842712e+00, 2.23606798e+00, 1.11803399e+01, 4.24264069e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 2.00000000e+00,
       1.41421356e+00, 1.00000000e+00, 1.41421356e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.41421356e+00, 1.41421356e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 2.23606798e+00,
       2.23606798e+00, 1.41421356e+00, 5.38516481e+00, 1.40356688e+01,
      

In [9]:
outliers = []
for i in range(len(previsoes)):
    #print(i)
    if previsoes[i] == 1:
        outliers.append(i)

In [10]:
print(outliers)

[3, 55, 57, 92, 104, 113, 115, 158, 169, 173, 229, 231, 242, 249, 312, 320, 334, 345, 347, 370, 378, 390, 405, 416, 461, 463, 464, 465, 466, 467, 468, 474, 475, 481, 486, 518, 519, 520, 521, 525, 532, 539, 540, 541, 543, 544, 577, 579, 580, 581, 582, 583, 584, 589, 590, 591, 595, 596, 597, 598]


In [11]:
lista_outliers = df.iloc[outliers,:]
lista_outliers

trace_id      timestamp  latency  succ      source  \
3    868d91717444d4112006  1587398400054     40.0  True  docker_004   
55   868d91717444d4112006  1587398400038     26.0  True      os_021   
57   868d91717444d4112006  1587398400017     27.0  True        None   
92   2190e1717444d4129924  1587398400224     54.0  True  docker_001   
104  2190e1717444d4129924  1587398400308     72.0  True  docker_001   
113  2190e1717444d4129924  1587398400037     40.0  True      os_022   
115  2190e1717444d4129924  1587398400018    153.0  True        None   
158  22bc21717444d4152360  1587398400228     57.0  True  docker_001   
169  22bc21717444d4152360  1587398400305     79.0  True  docker_001   
173  22bc21717444d4152360  1587398400022   4593.0  True        None   
229  b9a0e1717444d4141834  1587398400038     41.0  True      os_021   
231  b9a0e1717444d4141834  1587398400020     29.0  True        None   
242  e941a1717444d41b6098  1587398400097     19.0  True  docker_004   
249  e941a1717444d41b6098  1587398400126     20.0  True  docker_004   
312  9c1041717444d41b2364  1587398400191     21.0  True  docker_001   
320  9c1041717444d41b2364  1587398400228     55.0  True  docker_001   
334  9c1041717444d41b2364  1587398400308     73.0  True  docker_001   
345  9c1041717444d41b2364  1587398400039     41.0  True      os_022   
347  9c1041717444d41b2364  1587398400027   4586.0  True        None   
370  f82a71717444d4129926  1587398400187     23.0  True  docker_001   
378  f82a71717444d4129926  1587398400224     57.0  True  docker_001   
390  f82a71717444d4129926  1587398400307     72.0  True  docker_001   
405  f82a71717444d4129926  1587398400018    158.0  True        None   
416  867531717444d4129928  1587398400101     19.0  True  docker_002   
461  867531717444d4129928  1587398400046     67.0  True      os_022   
463  867531717444d4129928  1587398400018     34.0  True        None   
464  fad941717444d5a09888  1587398400531      3.0  True  docker_007   
465  fad941717444d5a09888  1587398400536      3.0  True  docker_007   
466  fad941717444d5a09888  1587398400531      2.0  True  docker_007   
467  fad941717444d5a09888  1587398400514     28.0  True  docker_002   
468  fad941717444d5a09888  1587398400512      0.0  True  docker_002   
474  fad941717444d5a09888  1587398400552     15.0  True  docker_002   
475  fad941717444d5a09888  1587398400550      0.0  True  docker_002   
481  fad941717444d5a09888  1587398400578     16.0  True  docker_002   
486  fad941717444d5a09888  1587398400608     16.0  True  docker_002   
518  fad941717444d5a09888  1587398400505      5.0  True  docker_002   
519  fad941717444d5a09888  1587398400501     24.0  True      os_022   
520  fad941717444d5a09888  1587398400499      0.0  True      os_022   
521  fad941717444d5a09888  1587398400416    129.0  True        None   
525  b41df1717444d6409894  1587398400614     29.0  True  docker_001   
532  b41df1717444d6409894  1587398400654     16.0  True  docker_001   
539  b41df1717444d6409894  1587398400683     16.0  True  docker_001   
540  b41df1717444d6409894  1587398400680      0.0  True  docker_001   
541  b41df1717444d6409894  1587398400718      3.0  True  docker_007   
543  b41df1717444d6409894  1587398400718      2.0  True  docker_007   
544  b41df1717444d6409894  1587398400713     15.0  True  docker_001   
577  b41df1717444d6409894  1587398400598     25.0  True      os_022   
579  b41df1717444d6409894  1587398400576     37.0  True        None   
580  ebcc41717444d6fa9900  1587398400826      3.0  True  docker_007   
581  ebcc41717444d6fa9900  1587398400830      3.0  True  docker_007   
582  ebcc41717444d6fa9900  1587398400826      1.0  True  docker_007   
583  ebcc41717444d6fa9900  1587398400808     30.0  True  docker_002   
584  ebcc41717444d6fa9900  1587398400806      0.0  True  docker_002   
589  ebcc41717444d6fa9900  1587398400861      3.0  True  docker_008   
590  ebcc41717444d6fa9900  1587398400847     15.0  True  docker_002   
591  ebcc41717444d6fa9900  1587398400845 