In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.font_manager

In [47]:
# from pyod.models.abod import ABOD
from pyod.models.knn import KNN

In [48]:
df = pd.read_csv("rca.csv")

In [49]:
df.head(10)

trace_id      timestamp  latency  succ      source      target
0  868d91717444d4112006  1587398400084      4.0  True  docker_005      db_003
1  868d91717444d4112006  1587398400090      2.0  True  docker_005      db_003
2  868d91717444d4112006  1587398400084      2.0  True  docker_005  docker_005
3  868d91717444d4112006  1587398400054     40.0  True  docker_004  docker_005
4  868d91717444d4112006  1587398400053      0.0  True  docker_004  docker_004
5  868d91717444d4112006  1587398400118      2.0  True  docker_005      db_003
6  868d91717444d4112006  1587398400122      2.0  True  docker_005      db_003
7  868d91717444d4112006  1587398400118      3.0  True  docker_005  docker_005
8  868d91717444d4112006  1587398400131      2.0  True  docker_005      db_003
9  868d91717444d4112006  1587398400129      2.0  True  docker_005  docker_005

In [50]:
detector = KNN()
detector.fit(df.iloc[:,1:4])

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [51]:
previsoes = detector.labels_
previsoes

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [52]:
np.unique(previsoes, return_counts=True)

(array([0, 1]), array([539,  60], dtype=int64))

In [53]:
confianca_previsoes = detector.decision_scores_
confianca_previsoes

array([1.41421356e+00, 2.00000000e+00, 1.41421356e+00, 1.40356688e+01,
       7.00000000e+00, 3.60555128e+00, 3.00000000e+00, 3.16227766e+00,
       2.00000000e+00, 2.00000000e+00, 9.48683298e+00, 2.00000000e+00,
       3.00000000e+00, 2.23606798e+00, 3.00000000e+00, 2.23606798e+00,
       3.60555128e+00, 7.81024968e+00, 3.00000000e+00, 2.23606798e+00,
       2.82842712e+00, 2.23606798e+00, 1.11803399e+01, 4.24264069e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 2.00000000e+00,
       1.41421356e+00, 1.00000000e+00, 1.41421356e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.41421356e+00, 1.41421356e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 2.23606798e+00,
       2.23606798e+00, 1.41421356e+00, 5.38516481e+00, 1.40356688e+01,
      

In [55]:
outliers = []
for i in range(len(previsoes)):
    print(i)
    if previsoes[i] == 1:
        outliers.append(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [56]:
print(outliers)

[3, 55, 57, 92, 104, 113, 115, 158, 169, 173, 229, 231, 242, 249, 312, 320, 334, 345, 347, 370, 378, 390, 405, 416, 461, 463, 464, 465, 466, 467, 468, 474, 475, 481, 486, 518, 519, 520, 521, 525, 532, 539, 540, 541, 543, 544, 577, 579, 580, 581, 582, 583, 584, 589, 590, 591, 595, 596, 597, 598]


In [57]:
lista_outliers = df.iloc[outliers,:]
lista_outliers

trace_id      timestamp  latency  succ      source  \
3    868d91717444d4112006  1587398400054     40.0  True  docker_004   
55   868d91717444d4112006  1587398400038     26.0  True      os_021   
57   868d91717444d4112006  1587398400017     27.0  True        None   
92   2190e1717444d4129924  1587398400224     54.0  True  docker_001   
104  2190e1717444d4129924  1587398400308     72.0  True  docker_001   
113  2190e1717444d4129924  1587398400037     40.0  True      os_022   
115  2190e1717444d4129924  1587398400018    153.0  True        None   
158  22bc21717444d4152360  1587398400228     57.0  True  docker_001   
169  22bc21717444d4152360  1587398400305     79.0  True  docker_001   
173  22bc21717444d4152360  1587398400022   4593.0  True        None   
229  b9a0e1717444d4141834  1587398400038     41.0  True      os_021   
231  b9a0e1717444d4141834  1587398400020     29.0  True        None   
242  e941a1717444d41b6098  1587398400097     19.0  True  docker_004   
249  e941a1717444d41b6098  1587398400126     20.0  True  docker_004   
312  9c1041717444d41b2364  1587398400191     21.0  True  docker_001   
320  9c1041717444d41b2364  1587398400228     55.0  True  docker_001   
334  9c1041717444d41b2364  1587398400308     73.0  True  docker_001   
345  9c1041717444d41b2364  1587398400039     41.0  True      os_022   
347  9c1041717444d41b2364  1587398400027   4586.0  True        None   
370  f82a71717444d4129926  1587398400187     23.0  True  docker_001   
378  f82a71717444d4129926  1587398400224     57.0  True  docker_001   
390  f82a71717444d4129926  1587398400307     72.0  True  docker_001   
405  f82a71717444d4129926  1587398400018    158.0  True        None   
416  867531717444d4129928  1587398400101     19.0  True  docker_002   
461  867531717444d4129928  1587398400046     67.0  True      os_022   
463  867531717444d4129928  1587398400018     34.0  True        None   
464  fad941717444d5a09888  1587398400531      3.0  True  docker_007   
465  fad941717444d5a09888  1587398400536      3.0  True  docker_007   
466  fad941717444d5a09888  1587398400531      2.0  True  docker_007   
467  fad941717444d5a09888  1587398400514     28.0  True  docker_002   
468  fad941717444d5a09888  1587398400512      0.0  True  docker_002   
474  fad941717444d5a09888  1587398400552     15.0  True  docker_002   
475  fad941717444d5a09888  1587398400550      0.0  True  docker_002   
481  fad941717444d5a09888  1587398400578     16.0  True  docker_002   
486  fad941717444d5a09888  1587398400608     16.0  True  docker_002   
518  fad941717444d5a09888  1587398400505      5.0  True  docker_002   
519  fad941717444d5a09888  1587398400501     24.0  True      os_022   
520  fad941717444d5a09888  1587398400499      0.0  True      os_022   
521  fad941717444d5a09888  1587398400416    129.0  True        None   
525  b41df1717444d6409894  1587398400614     29.0  True  docker_001   
532  b41df1717444d6409894  1587398400654     16.0  True  docker_001   
539  b41df1717444d6409894  1587398400683     16.0  True  docker_001   
540  b41df1717444d6409894  1587398400680      0.0  True  docker_001   
541  b41df1717444d6409894  1587398400718      3.0  True  docker_007   
543  b41df1717444d6409894  1587398400718      2.0  True  docker_007   
544  b41df1717444d6409894  1587398400713     15.0  True  docker_001   
577  b41df1717444d6409894  1587398400598     25.0  True      os_022   
579  b41df1717444d6409894  1587398400576     37.0  True        None   
580  ebcc41717444d6fa9900  1587398400826      3.0  True  docker_007   
581  ebcc41717444d6fa9900  1587398400830      3.0  True  docker_007   
582  ebcc41717444d6fa9900  1587398400826      1.0  True  docker_007   
583  ebcc41717444d6fa9900  1587398400808     30.0  True  docker_002   
584  ebcc41717444d6fa9900  1587398400806      0.0  True  docker_002   
589  ebcc41717444d6fa9900  1587398400861      3.0  True  docker_008   
590  ebcc41717444d6fa9900  1587398400847     15.0  True  docker_002   
591  ebcc41717444d6fa9900  1587398400845 