In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.font_manager

In [2]:
from pyod.models.abod import ABOD

In [3]:
df = pd.read_csv("rca.csv")

In [4]:
df.head(100)

trace_id      timestamp  latency  succ      source      target
0   868d91717444d4112006  1587398400084      4.0  True  docker_005      db_003
1   868d91717444d4112006  1587398400090      2.0  True  docker_005      db_003
2   868d91717444d4112006  1587398400084      2.0  True  docker_005  docker_005
3   868d91717444d4112006  1587398400054     40.0  True  docker_004  docker_005
4   868d91717444d4112006  1587398400053      0.0  True  docker_004  docker_004
..                   ...            ...      ...   ...         ...         ...
95  2190e1717444d4129924  1587398400290      1.0  True  docker_001      db_009
96  2190e1717444d4129924  1587398400287      4.0  True  docker_001  docker_001
97  2190e1717444d4129924  1587398400296      1.0  True  docker_001      db_009
98  2190e1717444d4129924  1587398400292      4.0  True  docker_001  docker_001
99  2190e1717444d4129924  1587398400300      1.0  True  docker_001      db_009

[100 rows x 6 columns]

In [5]:
detector = ABOD()
detector.fit(df.iloc[:,1:4])

ABOD(contamination=0.1, method='fast', n_neighbors=5)

In [6]:
previsoes = detector.labels_
previsoes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [7]:
np.unique(previsoes, return_counts=True)

(array([0, 1]), array([539,  60], dtype=int64))

In [8]:
confianca_previsoes = detector.decision_scores_
confianca_previsoes

array([-5.55555556e-02, -1.80555556e-01, -1.66666667e-01, -1.90260572e-03,
       -3.40490363e-02, -1.28357396e-01, -3.95138889e-02, -5.44555556e-02,
       -1.40625000e-01, -4.40625000e-01, -1.04952406e-04, -1.72500000e-01,
       -2.06481481e-02, -2.66666667e-02, -2.06481481e-02, -1.99000000e-02,
       -2.97748678e-03, -7.61798799e-04, -3.84355710e-02, -1.21388889e-01,
       -8.00000000e-02, -1.21388889e-01, -5.63173680e-05, -3.34849879e-03,
       -2.50000000e-01, -4.72222222e-01, -2.22222222e-01, -0.00000000e+00,
       -3.60000000e-01, -0.00000000e+00, -0.00000000e+00, -9.60000000e-01,
       -8.88888889e-01, -0.00000000e+00, -8.88888889e-01, -1.38888889e-02,
       -2.50000000e-01, -4.72222222e-01, -2.84722222e-01, -8.88888889e-01,
       -8.88888889e-01, -8.88888889e-01, -8.88888889e-01, -6.00000000e-01,
       -4.72222222e-01, -1.18055556e-01, -1.40000000e-01, -0.00000000e+00,
       -3.33333333e-01, -2.22222222e-01, -9.60000000e-01, -4.96000000e-02,
       -2.94560000e-02, -

In [9]:
outliers = []
for i in range(len(previsoes)):
    #print(i)
    if previsoes[i] == 1:
        outliers.append(i)

In [10]:
print(outliers)

[27, 29, 30, 33, 47, 55, 66, 83, 115, 145, 146, 148, 149, 173, 191, 193, 195, 196, 198, 200, 234, 246, 248, 249, 267, 270, 271, 283, 296, 347, 356, 357, 370, 405, 423, 455, 456, 458, 459, 461, 467, 468, 474, 481, 486, 518, 519, 520, 521, 525, 532, 539, 544, 576, 577, 579, 583, 584, 590, 597]


In [11]:
lista_outliers = df.iloc[outliers,:]
lista_outliers

trace_id      timestamp  latency  succ      source  \
27   868d91717444d4112006  1587398400203      1.0  True  docker_004   
29   868d91717444d4112006  1587398400205      1.0  True  docker_004   
30   868d91717444d4112006  1587398400204      1.0  True  docker_004   
33   868d91717444d4112006  1587398400209      1.0  True  docker_004   
47   868d91717444d4112006  1587398400223      1.0  True  docker_004   
55   868d91717444d4112006  1587398400038     26.0  True      os_021   
66   2190e1717444d4129924  1587398400133      2.0  True  docker_008   
83   2190e1717444d4129924  1587398400209      1.0  True  docker_001   
115  2190e1717444d4129924  1587398400018    153.0  True        None   
145  22bc21717444d4152360  1587398400204      1.0  True  docker_001   
146  22bc21717444d4152360  1587398400203      1.0  True  docker_001   
148  22bc21717444d4152360  1587398400205      1.0  True  docker_001   
149  22bc21717444d4152360  1587398400209      1.0  True  docker_001   
173  22bc21717444d4152360  1587398400022   4593.0  True        None   
191  b9a0e1717444d4141834  1587398400143     27.0  True  docker_003   
193  b9a0e1717444d4141834  1587398400209      2.0  True  docker_006   
195  b9a0e1717444d4141834  1587398400209      2.0  True  docker_006   
196  b9a0e1717444d4141834  1587398400205     13.0  True  docker_003   
198  b9a0e1717444d4141834  1587398400223      1.0  True  docker_003   
200  b9a0e1717444d4141834  1587398400223      1.0  True  docker_003   
234  e941a1717444d41b6098  1587398400076      5.0  True  docker_005   
246  e941a1717444d41b6098  1587398400133      2.0  True  docker_005   
248  e941a1717444d41b6098  1587398400144      7.0  True  docker_005   
249  e941a1717444d41b6098  1587398400126     20.0  True  docker_004   
267  e941a1717444d41b6098  1587398400203      1.0  True  docker_004   
270  e941a1717444d41b6098  1587398400205      1.0  True  docker_004   
271  e941a1717444d41b6098  1587398400209      1.0  True  docker_004   
283  e941a1717444d41b6098  1587398400223      1.0  True  docker_004   
296  9c1041717444d41b2364  1587398400133      2.0  True  docker_007   
347  9c1041717444d41b2364  1587398400027   4586.0  True        None   
356  f82a71717444d4129926  1587398400134      3.0  True  docker_007   
357  f82a71717444d4129926  1587398400133      2.0  True  docker_007   
370  f82a71717444d4129926  1587398400187     23.0  True  docker_001   
405  f82a71717444d4129926  1587398400018    158.0  True        None   
423  867531717444d4129928  1587398400138     15.0  True  docker_002   
455  867531717444d4129928  1587398400204      1.0  True  docker_002   
456  867531717444d4129928  1587398400203      1.0  True  docker_002   
458  867531717444d4129928  1587398400209      2.0  True  docker_002   
459  867531717444d4129928  1587398400205      1.0  True  docker_002   
461  867531717444d4129928  1587398400046     67.0  True      os_022   
467  fad941717444d5a09888  1587398400514     28.0  True  docker_002   
468  fad941717444d5a09888  1587398400512      0.0  True  docker_002   
474  fad941717444d5a09888  1587398400552     15.0  True  docker_002   
481  fad941717444d5a09888  1587398400578     16.0  True  docker_002   
486  fad941717444d5a09888  1587398400608     16.0  True  docker_002   
518  fad941717444d5a09888  1587398400505      5.0  True  docker_002   
519  fad941717444d5a09888  1587398400501     24.0  True      os_022   
520  fad941717444d5a09888  1587398400499      0.0  True      os_022   
521  fad941717444d5a09888  1587398400416    129.0  True        None   
525  b41df1717444d6409894  1587398400614     29.0  True  docker_001   
532  b41df1717444d6409894  1587398400654     16.0  True  docker_001   
539  b41df1717444d6409894  1587398400683     16.0  True  docker_001   
544  b41df1717444d6409894  1587398400713     15.0  True  docker_001   
576  b41df1717444d6409894  1587398400602      7.0  True  docker_001   
577  b41df1717444d6409894  1587398400598     25.0  True      os_022   
579  b41df1717444d6409894  1587398400576 